import type {TestRecord} from "./types";
import {defaultPedals} from "./pedalCatalog";
import {defaultAmpCatalog,instantiateAmp} from "./ampCatalog";
export const emptyTest=():TestRecord=>({
 id:"",artistReference:"",song:"",date:new Date().toISOString().slice(0,10),status:"À tester",
 guitar:"",tuning:"",pickup:"",cabinet:"",
 amp:instantiateAmp(defaultAmpCatalog[0]),
 pedals:defaultPedals(),
 otherPedals:"",objective:"",observations:"",conclusion:"",retained:false
});
export const sampleTests:TestRecord[]=[
 {id:"TD-001",artistReference:"The Darkness",song:"Love on the rocks",date:"2026-08-31",status:"Prometteur",guitar:"Gibson Les Paul Classic DC",tuning:"Standard",pickup:"Chevalet",cabinet:"2x12 Closed V70",amp:{templateId:"brunetti-xl-revo2",name:"Brunetti XL R-EVO II",channel:"Boost",params:[{name:"Gain",kind:"knob",value:"2"},{name:"Bass",kind:"knob",value:"3.5"},{name:"Mid",kind:"knob",value:"6"},{name:"Edge",kind:"knob",value:"5"},{name:"Master",kind:"knob",value:"3.5"},{name:"Bright",kind:"knob",value:"",onlyChannels:["Clean"]},{name:"Focus",kind:"knob",value:"5.5",min:0,max:10,step:0.5,onlyChannels:["Boost","XLead"]},{name:"Depth",kind:"knob",value:"8.5"},{name:"Level",kind:"knob",value:"2"}]},pedals:[{id:"pedal-1788035013363-c",name:"Ibanez Tube Screamer (TS9 / TS808)",enabled:"ON",notes:"",params:[{name:"Drive",kind:"knob",value:"1.5"},{name:"Tone",kind:"knob",value:"3.5"},{name:"Level",kind:"knob",value:"8"}],templateId:"tube-screamer"},{id:"pedal-1788035013363-d",name:"MXR M109S Six Band EQ",enabled:"ON",notes:"",params:[{name:"100 Hz",kind:"slider",value:"3",min:-18,max:18,step:0.5},{name:"200 Hz",kind:"slider",value:"0.5",min:-18,max:18,step:0.5},{name:"400 Hz",kind:"slider",value:"1.5",min:-18,max:18,step:0.5},{name:"800 Hz",kind:"slider",value:"2",min:-18,max:18,step:0.5},{name:"1.6 kHz",kind:"slider",value:"0",min:-18,max:18,step:0.5},{name:"3.2 kHz",kind:"slider",value:"0",min:-18,max:18,step:0.5}],templateId:"mxr-6-band-eq"},{id:"pedal-1788035013363-e",name:"Mooer Graphic G",enabled:"ON",notes:"",params:[{name:"100 Hz",kind:"slider",value:"0",min:-18,max:18,step:0.5},{name:"250 Hz",kind:"slider",value:"0",min:-18,max:18,step:0.5},{name:"630 Hz",kind:"slider",value:"1",min:-18,max:18,step:0.5},{name:"1.6 kHz",kind:"slider",value:"2.5",min:-18,max:18,step:0.5},{name:"4 kHz",kind:"slider",value:"0",min:-18,max:18,step:0.5},{name:"Level",kind:"knob",value:"1.5",min:-5,max:5,step:0.5}],templateId:"mooer-graphic-g"}],otherPedals:"",objective:"",observations:"",conclusion:"",retained:false},

 {id:"ACDC-001",artistReference:"ACDC",song:"Back in Black",date:"2026-08-31",status:"À tester",guitar:"Gibson Les Paul Classic DC",tuning:"Standard",pickup:"",cabinet:"Marshall 4x12",amp:{templateId:"amptpl-1787349577156",name:"Gibson Skylark 5w",channel:"Principal",params:[{name:"Master",kind:"knob",value:"10"}]},otherPedals:"",objective:"Chercher une base Stoner dense",observations:"",conclusion:"",retained:false,pedals:[{id:"pedal-1787245400337-13pfz",name:"Ibanez Tube Screamer (TS9 / TS808)",enabled:"ON",notes:"",params:[{name:"Drive",kind:"knob",value:"2.5"},{name:"Tone",kind:"knob",value:"2.5"},{name:"Level",kind:"knob",value:"8"}],templateId:"tube-screamer"},{id:"pedal-1787263092182-1a14s",name:"MXR M109S Six Band EQ",enabled:"OFF",notes:"",params:[{name:"100 Hz",kind:"slider",value:"0",min:-18,max:18,step:0.5},{name:"200 Hz",kind:"slider",value:"0",min:-18,max:18,step:0.5},{name:"400 Hz",kind:"slider",value:"0",min:-18,max:18,step:0.5},{name:"800 Hz",kind:"slider",value:"0",min:-18,max:18,step:0.5},{name:"1.6 kHz",kind:"slider",value:"0",min:-18,max:18,step:0.5},{name:"3.2 kHz",kind:"slider",value:"0",min:-18,max:18,step:0.5}],templateId:"mxr-6-band-eq"}]},
 {id:"FF-001",artistReference:"Foo Fighters",song:"Low",date:"2026-08-31",status:"À tester",guitar:"Gretsch Gourley Broadkaster",tuning:"Drop C#",pickup:"Middle",cabinet:"2x12 Closed V70",amp:{templateId:"brunetti-xl-revo2",name:"Brunetti XL R-EVO II",channel:"XLead",params:[{name:"Gain",kind:"knob",value:"1.5"},{name:"Bass",kind:"knob",value:"5"},{name:"Mid",kind:"knob",value:"7"},{name:"Edge",kind:"knob",value:"5"},{name:"Master",kind:"knob",value:"3"},{name:"Bright",kind:"knob",value:"",onlyChannels:["Clean"]},{name:"Focus",kind:"knob",value:"3.5",min:0,max:10,step:0.5,onlyChannels:["Boost","XLead"]},{name:"Depth",kind:"knob",value:"6.5"},{name:"Level",kind:"knob",value:"4"}]},otherPedals:"",objective:"Base Rock dynamique",observations:"",conclusion:"",retained:false,pedals:[{id:"Tube Screamer",name:"Tube Screamer",enabled:"ON",notes:"",params:[{name:"Drive",kind:"knob",value:"2"},{name:"Tone",kind:"knob",value:"4"},{name:"Level",kind:"knob",value:"7.5"}],templateId:"tube-screamer"},{id:"MXR 6 Band EQ",name:"MXR 6 Band EQ",enabled:"OFF",notes:"",params:[{name:"100 Hz",kind:"slider",value:"",min:-18,max:18,step:0.5},{name:"200 Hz",kind:"slider",value:"",min:-18,max:18,step:0.5},{name:"400 Hz",kind:"slider",value:"",min:-18,max:18,step:0.5},{name:"800 Hz",kind:"slider",value:"",min:-18,max:18,step:0.5},{name:"1.6 kHz",kind:"slider",value:"",min:-18,max:18,step:0.5},{name:"3.2 kHz",kind:"slider",value:"",min:-18,max:18,step:0.5}],templateId:"mxr-6-band-eq"},{id:"Mooer Graphic G",name:"Mooer Graphic G",enabled:"OFF",notes:"",params:[{name:"100 Hz",kind:"slider",value:"",min:-18,max:18,step:0.5},{name:"250 Hz",kind:"slider",value:"",min:-18,max:18,step:0.5},{name:"630 Hz",kind:"slider",value:"",min:-18,max:18,step:0.5},{name:"1.6 kHz",kind:"slider",value:"",min:-18,max:18,step:0.5},{name:"4 kHz",kind:"slider",value:"",min:-18,max:18,step:0.5},{name:"Level",kind:"knob",value:"0",min:-5,max:5,step:0.5}],templateId:"mooer-graphic-g"}]}
];